In [3]:
# Work with scalar, vectors and matrices in Python using numpy
import numpy as np

In [ ]:
s = 5.2

In [ ]:
print(s)

5.2


In [ ]:
# Declare a vector
v = np.array([5,-2,4])

In [ ]:
print(v)

[ 5 -2  4]


In [4]:
# Declare a matrix
m = np.array([[5,12,6],[-3,0,14]])

In [ ]:
print(m)

[[ 5 12  6]
 [-3  0 14]]


In [ ]:
type(s)

float

In [ ]:
type(m)

numpy.ndarray

In [ ]:
type(v)

numpy.ndarray

In [ ]:
# To return the shape or dimension of the matrix m
m.shape

(2, 3)

In [ ]:
# To return the shape or dimension of the vector v
v.shape

(3,)

In [5]:
print(m)

[[ 5 12  6]
 [-3  0 14]]


In [6]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [7]:
m1 = np.array([[9,8,7],[1,3,-5]])

In [8]:
m1

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [9]:
#Define Matrix t using the matrices m and m1
t=np.array([m,m1])

In [10]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [11]:
# Display the shape of matrix t
t.shape

(2, 2, 3)

In [12]:
# Adding matrices
m2 = m + m1

In [13]:
m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [14]:
# Subtracting the matrices
m2 = m - m

In [15]:
m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [16]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [18]:
print(v1+v2)

[6 6 6 6 6]


In [19]:
v1-v2

array([-4, -2,  0,  2,  4])

In [20]:
# Transposong in quality
# Changed 0to Fo
m2.transpose

<function ndarray.transpose>

In [21]:
  m2.T

array([[-4, -4],
       [ 4, -3],
       [-1, 19]])

In [29]:
# Create vector 
v3 = np.array([2,8,-4])

In [30]:
v3

array([ 2,  8, -4])

In [24]:
v3.shape

(3,)

In [25]:
v4  = np.array([1,-7,3])

In [26]:
v4

array([ 1, -7,  3])

In [27]:
v3 * v4

array([  2, -56,  12])

In [31]:
# The dot product for vectors v3 & v4
np.dot(v3,v4)

-66

In [33]:
# Create the vector
r = np.array([0,2,5,8])
s = np.array([20,3,4,-1])

In [34]:
np.dot(r,s)

18

In [35]:
v3

array([ 2,  8, -4])

In [36]:
# Multiply a scalar by the given array
5*v3

array([ 10,  40, -20])